DIRECTION_VECTOR_UP = (0, -1)
DIRECTION_VECTOR_DOWN = (0, 1)
DIRECTION_VECTOR_LEFT = (-1, 0)
DIRECTION_VECTOR_RIGHT = (1, 0)

DIRECTION_UP : int = 0
DIRECTION_DOWN : int = 1
DIRECTION_LEFT : int = 2
DIRECTION_RIGHT : int = 3

DIRECTION_VECTORS  = [
	DIRECTION_VECTOR_UP,
	DIRECTION_VECTOR_DOWN,
	DIRECTION_VECTOR_LEFT,
	DIRECTION_VECTOR_RIGHT,
]