DIRECTION_VECTOR_UP : tuple[int, int] = (0, -1)
DIRECTION_VECTOR_DOWN : tuple[int, int] = (0, 1)
DIRECTION_VECTOR_LEFT : tuple[int, int] = (-1, 0)
DIRECTION_VECTOR_RIGHT : tuple[int, int] = (1, 0)

DIRECTION_UP : int = 0
DIRECTION_DOWN : int = 1
DIRECTION_LEFT : int = 2
DIRECTION_RIGHT : int = 3

DIRECTION_VECTORS : list[tuple[int, int]] = [
	DIRECTION_VECTOR_UP,
	DIRECTION_VECTOR_DOWN,
	DIRECTION_VECTOR_LEFT,
	DIRECTION_VECTOR_RIGHT,
]